import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import Calendar from 'react-calendar';
import 'react-calendar/dist/Calendar.css';
import Layout from '../components/Layout';
import DatePicker from 'react-datepicker';
import Modal from '../components/Modal';
import { useSelector, useDispatch } from 'react-redux';
import { toggleModalAC } from '../redux/actions/task_actions';

import 'react-datepicker/dist/react-datepicker.css';

export default function Home() {
  const [startDate, setStartDate] = useState(new Date());
  const [day, setDay] = useState('Today');
  const [tomorrow, setTomorrow] = useState(false);
  const dispatch = useDispatch();
  const { modal_show } = useSelector((state) => state.task);
  //low_opacity
  console.log('modal_show: ', modal_show);
  const handleDayBtn = (e) => {
    debugger;
    setDay(e.target.outerText);
    console.log(day);

    if (e.target.outerText === 'Tomorrow') {
      debugger;
      let day = startDate.getDate() + 1;
      let month = startDate.getMonth();
      let year = startDate.getFullYear();
      let str = `${day}, ${month}, ${year}`;
      let newDate = new Date(year, month, day);
      if (!tomorrow) {
        setStartDate(newDate);
      }
      setTomorrow(true);
    } else if (e.target.outerText === 'Today') {
      let today = new Date();
      setStartDate(today);
      setTomorrow(false);
    }
  };
  const toggleModal = () => {
    debugger;
    dispatch(toggleModalAC());
  };
  return (
    <div>
      <Head>
        <title>Task Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Luxurious+Roman&family=Montserrat+Alternates:ital,wght@1,400;1,500;1,700;1,900&family=Outfit:wght@400;700&family=Spline+Sans:wght@500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      {modal_show && <Modal />}
      <Layout>
        {
          <div
            className={
              modal_show ? 'wrapper low_opacity container' : 'wrapper container'
            }
          >
            <div className="sidebar">
              <DatePicker
                selected={startDate}
                inline
                onChange={(date) => setStartDate(date)}
              />
              <button onClick={toggleModal} className="makeTaskBtn">
                Make New Task
              </button>
            </div>
            <div className="main">
              <div className="links">
                <a
                  href="#"
                  onClick={handleDayBtn}
                  className={day == 'Today' ? 'selected' : ''}
                >
                  Today
                </a>
                <a
                  href="#"
                  onClick={handleDayBtn}
                  className={day == 'Tomorrow' ? 'selected' : ''}
                >
                  Tomorrow
                </a>
              </div>
              <div className="table">
                <div className="new_request">New Requests</div>
                <div className="in_progress">In Progress</div>
                <div className="done">Done</div>
              </div>
            </div>
          </div>
        }
      </Layout>
    </div>
  );
}
